### ISSUE TITLE
Nanoserver 1809 ContainerAdministrator user

### ISSUE THREAD

**Issue by joostmeijles** [sitecoreops/sitecore-images#27]
We had a permission issue with our Solr Nanoserver 1809 based image. It turned out that the copied files did not have the correct permissions set. As solution we chose to set the `ContainerAdministrator` user: https://github.com/avivasolutionsnl/sitecore-docker/pull/88/files

I noticed that you removed the `ContainerAdministrator` in: https://github.com/sitecoreops/sitecore-images/blob/master/images/9.0.2%20rev.%20180604/nanoserver-1809/sitecore-solr/Dockerfile

While it was present in:
https://github.com/sitecoreops/sitecore-images/blob/57317622e1d09e912601f18f011c5ce19d0b821c/images/9.0.2%20rev.%20180604/nanoserver-1803/sitecore-xp-solr/Dockerfile#L62

Do you not have this permission issue with nanoserver 1809?

**Comment by pbering** [comment]
Hi there, when switching from 1803 to 1809 I removed the `USER ContainerAdministrator` since it's not needed anymore due to the drive mapping stuff is also not needed anymore. I havn't seen any permission issues while starting up solr or rebuilding cores, but I don't have any "real" solutions yet other that the test that runs on 1809, so there could be an issue that I just havn't see yet. How do you see the permission issues?

**Comment by joostmeijles** [comment]
I got errors at Solr startup that log files could not be created.

**Comment by pbering** [comment]
hmm having a hard time to reproduce this. Have trying various combinations of running hyperv/process isolation and from elevated powershell session and not. Can you provide me with the output from solr?

**Comment by joostmeijles** [comment]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/4342282/56016345-33acfe00-5cfc-11e9-9af0-ec5e0319b493.png)

Please note that my host is Windows 10 v1809 with process isolation.

**Comment by pbering** [comment]
Still couln't reproduce on Windows 10, but I got the same error on Windows Server 2019 in swarm mode. All 1809 solr images now runs as `ContainerAdministrator` again. Thank you :)
